name: Run Scraper

on:
  schedule:
    - cron: "*/15 10-23 * * *"   # Ejecutar cada 5 minutos entre las 7:00 y 21:00 horas Arg

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: create env file
        run: |
          touch .env
          echo CHAT_ID=${{ secrets.CHAT_ID }} >> .env
          echo TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }} >> .env
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Run Scraper
        run: npm start
